name: Main Pipeline

on:
   push:
      branches:
         - main

jobs:
   bump_version:
      name: Bump Cargo.toml Version
      runs-on: ubuntu-latest
      permissions:
         contents: write
      steps:
         -  name: Check out repo
            uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
            # https://github.com/actions/checkout
            with:
               fetch-depth: 0

         -  name: Bump Cargo.toml version
            uses: TriPSs/conventional-changelog-action@952b14bbc4be87e8458a6ac5926fc655608b1b19 # v6.3.1
            # https://github.com/TriPSs/conventional-changelog-action
            with:
               git-message: 'chore: Bumping Alf version to {version}'
               git-user-name: 'Conventional Changelog Action'
               git-user-email: 'changelog-updates@actions.anewlevelmedia.com'
               github-token: ${{ github.token }}
               output-file: 'false'
               preset: conventionalcommits
               skip-git-pull: 'true'
               skip-on-empty: 'true'
               tag-prefix: ''
               version-file: './Cargo.toml'
