name: Run Unit Tests

on:
   pull_request:
      branches:
         - main
         - 'ALF-[0-9]+'

jobs:
   test:
      name: Run All Unit Tests
      runs-on: ubuntu-latest
      permissions:
         contents: read
      steps:
         -  name: Check out repo
            uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
            # https://github.com/actions/checkout
            with:
               persist-credentials: false

         -  name: Install Rust toolchain
            uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

         -  name: Cache cargo registry & build
            uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

         -  name: Install cargo-nextest
            uses: taiki-e/install-action@16a76bb73558798e4218983c40c25fee9f2f99a8 # nextest

         -  name: Run tests
            run: make test
